language: php
php:
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"

before_script:
  - composer install
  
after_script:
  - export COVERALLS_RUN_LOCALLY=1
  - php bin/coveralls -v

script: 
  - bin/phpunit --coverage-text

matrix:
     allow_failures:
         - php: "hhvm"
